"""Table of locations that are available"""
import dataclasses


@dataclasses.dataclass
class Check:
    """Class that defines locations for locations"""

    name: str
    address: int
    flag: int
    region: bool
    displacement: int


location_table: list[Check] = [
    Check("Agitha Female Ant Reward", 0x804069E4, 0x80, False, -1),
    Check("Agitha Female Beetle Reward", 0x804069E1, 0x8, False, -1),
    Check("Agitha Female Butterfly Reward", 0x804069E1, 0x2, False, -1),
    Check("Agitha Female Dayfly Reward", 0x804069E4, 0x20, False, -1),
    Check("Agitha Female Dragonfly Reward", 0x804069E3, 0x2, False, -1),
    Check("Agitha Female Grasshopper Reward", 0x804069E2, 0x20, False, -1),
    Check("Agitha Female Ladybug Reward", 0x804069E3, 0x20, False, -1),
    Check("Agitha Female Mantis Reward", 0x804069E3, 0x80, False, -1),
    Check("Agitha Female Phasmid Reward", 0x804069E2, 0x8, False, -1),
    Check("Agitha Female Pill Bug Reward", 0x804069E2, 0x2, False, -1),
    Check("Agitha Female Snail Reward", 0x804069E3, 0x8, False, -1),
    Check("Agitha Female Stag Beetle Reward", 0x804069E2, 0x80, False, -1),
    Check("Agitha Male Ant Reward", 0x804069E3, 0x1, False, -1),
    Check("Agitha Male Beetle Reward", 0x804069E1, 0x10, False, -1),
    Check("Agitha Male Butterfly Reward", 0x804069E1, 0x4, False, -1),
    Check("Agitha Male Dayfly Reward", 0x804069E4, 0x40, False, -1),
    Check("Agitha Male Dragonfly Reward", 0x804069E3, 0x4, False, -1),
    Check("Agitha Male Grasshopper Reward", 0x804069E2, 0x40, False, -1),
    Check("Agitha Male Ladybug Reward", 0x804069E3, 0x40, False, -1),
    Check("Agitha Male Mantis Reward", 0x804069E2, 0x1, False, -1),
    Check("Agitha Male Phasmid Reward", 0x804069E2, 0x10, False, -1),
    Check("Agitha Male Pill Bug Reward", 0x804069E2, 0x4, False, -1),
    Check("Agitha Male Snail Reward", 0x804069E3, 0x10, False, -1),
    Check("Agitha Male Stag Beetle Reward", 0x804069E1, 0x1, False, -1),
    Check("Ariters Grounds Big Key Chest", 0x80406610, 0x10, True, 0x1),
    Check("Arbiters Grounds Death Sword Chest", 0x80406610, 0x8, True, 0x2),
    Check(
        "Arbiters Grounds East Lower Turnable Redead Chest",
        0x80406610,
        0x40,
        True,
        0x3,
    ),
    Check("Arbiters Grounds East Turning Room Poe", 0x80406610, 0x10, True, 0xA),
    Check("Arbiters Grounds East Upper Turnable Chest", 0x80406610, 0x10, True, 0x3),
    Check(
        "Arbiters Grounds East Upper Turnable Redead Chest", 0x80406610, 0x20, True, 0x3
    ),
    Check("Arbiters Grounds Entrance Chest", 0x80406610, 0x80, True, 0x0),
    Check("Arbiters Grounds Ghoul Rat Room Chest", 0x80406610, 0x20, True, 0x1),
    Check("Arbiters Grounds Hidden Wall Poe", 0x80406610, 0x4, True, 0x11),
    Check("Arbiters Grounds North Turning Room Chest", 0x80406610, 0x1, True, 0x0),
    Check(
        "Arbiters Grounds Spinner Room First Small Chest", 0x80406610, 0x10, True, 0x0
    ),
    Check(
        "Arbiters Grounds Spinner Room Lower Central Small Chest",
        0x80406610,
        0x20,
        True,
        0x0,
    ),
    Check(
        "Arbiters Grounds Spinner Room Lower North Chest", 0x80406610, 0x40, True, 0x0
    ),
    Check(
        "Arbiters Grounds Spinner Room Second Small Chest", 0x80406610, 0x8, True, 0x0
    ),
    Check(
        "Arbiters Grounds Spinner Room Stalfos Alcove Chest", 0x80406610, 0x4, True, 0x0
    ),
    Check("Arbiters Grounds Stallord Heart Container", 0x80406610, 0x10, True, 0x1D),
    Check("Arbuters Grounds Torch Room East Chest", 0x80406610, 0x8, True, 0x1),
    Check("Arbiters Grounds Torch Room Poe", 0x80406610, 0x40, True, 0x8),
    Check("Arbiters Grounds Torch Room West Chest", 0x80406610, 0x4, True, 0x1),
    Check("Arbiters Grounds West Chandelier Chest", 0x80406610, 0x8, True, 0x3),
    Check("Arbiters Grounds West Poe", 0x80406610, 0x2, True, 0xF),
    Check("Arbiters Grounds West Small Chest Behind Block", 0x80406610, 0x2, True, 0x0),
    Check("Arbiters Grounds West Stalfos Northeast Cave", 0x80406610, 0x1, True, 0x1),
    Check("Arbiters Grounds West Stalfos West Chest", 0x80406610, 0x2, True, 0x1),
    Check("Ashei Sketch", -1, -1, -1, -1),
    Check("Auru Gift to Fyer", -1, -1, -1, -1),
    Check("Barnes Bomb Bag", 0x804069B9, 0x8, False, -1),
    Check("Bridge of Eldin Female Phasmid", -1, -1, -1, -1),
    Check("Bridge of Elldin Male Phasmid", -1, -1, -1, -1),
    Check("Bridge of Eldin Owl Statue Chest", -1, -1, -1, -1),
    Check("Bridge of Eldin Owl Statue Sky Character", -1, -1, -1, -1),
    Check("Bulblin Camp First Chest Under Tower At Entrance", -1, -1, -1, -1),
    Check("Bulblin Camp Poe", -1, -1, -1, -1),
    Check("Bulblin Camp Roasted Boar", -1, -1, -1, -1),
    Check("Bulblin Camp Small Chest in Back of Camp", -1, -1, -1, -1),
    Check("Bulblin Guard Key", -1, -1, -1, -1),
    Check("Castle Town Malo Mart Magic Armor", -1, -1, -1, -1),
    Check("Cats Hide and Seek Minigame", -1, -1, -1, -1),
    Check("Cave of Ordeals Floor 17 Poe", -1, -1, -1, -1),
    Check("Cave of Ordeals Floor 33 Poe", -1, -1, -1, -1),
    Check("Cave of Ordeals Floor 44 Poe", -1, -1, -1, -1),
    Check("Cave of Ordeals Great Fairy Rewards", -1, -1, -1, -1),
    Check("Charlo Donation Blessing", -1, -1, -1, -1),
    Check("City in the Sky Aeralfos Chest", 0x80406670, 0x1, True, 0x3),
    Check("City in the Sky Argorok Heart Container", 0x80406670, 0x10, True, 0x1D),
    Check("City in the Sky Baba Tower Alcove Chest", 0x80406670, 0x40, True, 0x3),
    Check("City in the Sky Baba Tower Narrow Ledge Chest", 0x80406670, 0x80, True, 0x1),
    Check("City in the Sky Baba Tower Top Small Chest", 0x80406670, 0x80, True, 0x3),
    Check("City in the Sky Big Key Chest", 0x80406670, 0x20, True, 0x2),
    Check("City in the Sky Central Outside Ledge Chest", 0x80406670, 0x1, True, 0x0),
    Check(
        "City in the Sky Central Outside Poe Island Chest", 0x80406670, 0x10, True, 0x2
    ),
    Check("City in the Sky Chest Behind North Fan", 0x80406670, 0x2, True, 0x1),
    Check("City in the Sky Chest Below Big Key Chest", 0x80406670, 0x40, True, 0x2),
    Check("City in the Sky Dungeon Reward", 0x80406670, 0x8, True, 0x1D),
    Check(
        "City in the Sky East First Wing Chest After Fans", 0x80406670, 0x4, True, 0x3
    ),
    Check("City in the Sky East Tile Worm Small Chest", 0x80406670, 0x8, True, 0x1),
    Check(
        "City in the Sky East Wing After Dinalfos Alcove Chest",
        0x80406670,
        0x4,
        True,
        0x1,
    ),
    Check(
        "City in the Sky East Wing after Dinalfos Ledge Chest",
        0x80406670,
        0x4,
        True,
        0x0,
    ),
    Check("City in the Sky East Wing Lower Level Chest", 0x80406670, 0x10, True, 0x3),
    Check("City in the Sky Garden Island Poe", 0x80406670, 0x10, True, 0x11),
    Check("City in the Sky Poe Above Central Fan", 0x80406670, 0x20, True, 0x11),
    Check("City in the Sky Underwater East Chest", 0x80406670, 0x8, True, 0x0),
    Check("City in the Sky Underwater West Chest", 0x80406670, 0x8, True, 0x3),
    Check("City in the Sky West Garden Corner Chest", 0x80406670, 0x80, True, 0x2),
    Check("City in the Sky West Garden Ledge Chest", 0x80406670, 0x2, True, 0x2),
    Check("City in the Sky West Garden Lone Island Chest", 0x80406670, 0x2, True, 0x0),
    Check("City in the Sky West Garden Lower Chest", 0x80406670, 0x8, True, 0x2),
    Check("City in the Sky West Wing Baba Balcony Chest", 0x80406670, 0x20, True, 0x1),
    Check("City in the Sky West Wing First Chest", 0x80406670, 0x20, True, 0x3),
    Check("City in the Sky West Wing Narrow Ledge Chest", 0x80406670, 0x10, True, 0x1),
    Check("City in the Sky West Wing Tile Worm Chest", 0x80406670, 0x40, True, 0x3),
    Check("Coro Bottle", -1, -1, -1, -1),
    Check("Death Mountain Alcove Chest", -1, -1, -1, -1),
    Check("Death Mountain Trail Poe", -1, -1, -1, -1),
    Check("Doctors Office Balcony Chest", -1, -1, -1, -1),
    Check("East Castle Town Bridge Poe", -1, -1, -1, -1),
    Check("Eldin Field Bomb Rock Chest", -1, -1, -1, -1),
    Check("Eldin Field Bomskit Grotto Lantern Chest", -1, -1, -1, -1),
    Check("Eldin Field Bomskit Grotto Left Chest", -1, -1, -1, -1),
    Check("Eldin Field Female Grasshopper", -1, -1, -1, -1),
    Check("Eldin Field Male Grasshopper", -1, -1, -1, -1),
    Check("Eldin Field Stalfos Grotto Left Small Chest", -1, -1, -1, -1),
    Check("Eldin Field Stalfos Grotto Right Small Chest", -1, -1, -1, -1),
    Check("Eldin Field Stalfos Grotto Stalfos Chest", -1, -1, -1, -1),
    Check("Eldin Field Water Bomb Fish Grotto Chest", -1, -1, -1, -1),
    Check("Eldin Lantern Cave First Chest", -1, -1, -1, -1),
    Check("Eldin Lantern Cave Lantern Chest", -1, -1, -1, -1),
    Check("Eldin Lantern Cave Poe", -1, -1, -1, -1),
    Check("Eldin Lantern Cave Second Chest", -1, -1, -1, -1),
    Check("Eldin Spring Underwater Chest", -1, -1, -1, -1),
    Check("Eldin Stockcave Lantern Chest", -1, -1, -1, -1),
    Check("Eldin Stockcave Lowest Chest", -1, -1, -1, -1),
    Check("Eldin Stockcave Upper Chest", -1, -1, -1, -1),
    Check("Faron Field Bridge Chest", -1, -1, -1, -1),
    Check("Faron Field Corner Grotto Left Chest", -1, -1, -1, -1),
    Check("Faron Field Corner Grotto Rear Chest", -1, -1, -1, -1),
    Check("Faron Field Corner Grotto Right Chest", -1, -1, -1, -1),
    Check("Faron Field Female Beetle", -1, -1, -1, -1),
    Check("Faron Field Male Beetle", -1, -1, -1, -1),
    Check("Faron Field Poe", -1, -1, -1, -1),
    Check("Faron Field Tree Heart Piece", -1, -1, -1, -1),
    Check("Faron Mist Cave Lantern Chest", -1, -1, -1, -1),
    Check("Faron Mist Cave Open Chest", -1, -1, -1, -1),
    Check("Faron Mist North Chest", -1, -1, -1, -1),
    Check("Faron Mist Poe", -1, -1, -1, -1),
    Check("Faron Mist South Chest", -1, -1, -1, -1),
    Check("Faron Mist Stump Chest", -1, -1, -1, -1),
    Check("Faron Woods Golden Wolf", -1, -1, -1, -1),
    Check("Faron Woods Owl Statue Chest", -1, -1, -1, -1),
    Check("Faron Woods Owl Statue Sky Character", -1, -1, -1, -1),
    Check("Fishing Hole Bottle", -1, -1, -1, -1),
    Check("Fishing Hole Heart Piece", -1, -1, -1, -1),
    Check("Flight By Fowl Fifth Platform Chest", -1, -1, -1, -1),
    Check("Flight By Fowl Fourth Platform Chest", -1, -1, -1, -1),
    Check("Flight By Fowl Ledge Poe", -1, -1, -1, -1),
    Check("Flight By Fowl Second Platform Chest", -1, -1, -1, -1),
    Check("Flight By Fowl Third Platform Chest", -1, -1, -1, -1),
    Check("Flight By Fowl Top Platform Reward", -1, -1, -1, -1),
    Check("Forest Temple Big Baba Key", 0x804065B0, 0x40, True, 0x3),
    Check("Forest Temple Big Key Chest", 0x804065B0, 0x40, True, 0x7),
    Check("Forest Temple Central Chest Behind Stairs", 0x804065B0, 0x20, True, 0x7),
    Check("Forest Temple Central Chest Hanging From Web", 0x804065B0, 0x10, True, 0x1),
    Check("Forest Temple Central North Chest", 0x804065B0, 0x80, True, 0x7),
    Check("Forest Temple Diababa Heart Container", 0x804065B0, 0x10, True, 0x1D),
    Check("Forest Temple Dungeon Reward", 0x804065B0, 0x8, True, 0x1D),
    Check("Forest Temple East Tile Worm Chest", 0x804065B0, 0x2, True, 0x3),
    Check("Forest Temple East Water Cave Chest", 0x804065B0, 0x4, True, 0x0),
    Check("Forest Temple Entrance Vines Chest", 0x804065B0, 0x80, True, 0x3),
    Check("Forest Temple Gale Boomerang", 0x804065B0, 0x80, True, 0x1D),
    Check("Forest Temple North Deku Like Chest", 0x804065B0, 0x4, True, 0x3),
    Check("Forest Temple Second Monkey Under Bridge Chest", 0x804065B0, 0x2, True, 0x2),
    Check("Forest Temple Totem Pole Chest", 0x804065B0, 0x2, True, 0x0),
    Check("Forest Temple West Deku Like Chest", 0x804065B0, 0x80, True, 0x0),
    Check(
        "Forest Temple West Tile Worm Chest Behind Stairs", 0x804065B0, 0x8, True, 0x1
    ),
    Check("Forest Temple West Tile Worm Room Vines Chest", 0x804065B0, 0x1, True, 0x0),
    Check("Forest Temple Windless Bridge Chest", 0x804065B0, 0x10, True, 0x3),
    Check("Gerudo Desert Campfire East Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Campfire North Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Campfire West Chest", -1, -1, -1, -1),
    Check("Gerudo Desert East Canyon Chest", -1, -1, -1, -1),
    Check("Gerudo Desert East Poe", -1, -1, -1, -1),
    Check("Gerudo Desert Female Dayfly", -1, -1, -1, -1),
    Check("Gerudo Desert Golden Wolf", -1, -1, -1, -1),
    Check("Gerudo Desert Lone Small Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Male Dayfly", -1, -1, -1, -1),
    Check("Gerudo Desert North Peahat Poe", -1, -1, -1, -1),
    Check("Gerudo Desert North Small Chest Before Bulblin Camp", -1, -1, -1, -1),
    Check("Gerudo Desert Northeast Chest Behind Gates", -1, -1, -1, -1),
    Check("Gerudo Desert Northwest Chest Behind Gates", -1, -1, -1, -1),
    Check("Gerudo Desert Owl Statue Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Owl Statue Sky Character", -1, -1, -1, -1),
    Check("Gerudo Desert Peahat Ledge Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Poe Above Cave of Ordeals", -1, -1, -1, -1),
    Check("Gerudo Desert Rock Grotto First Poe", -1, -1, -1, -1),
    Check("Gerudo Desert Rock Grotto Lantern Chest", -1, -1, -1, -1),
    Check("Gerudo Desert Rock Grotto Second Poe", -1, -1, -1, -1),
    Check("Gerudo Desert Skulltula Grotto Chest", -1, -1, -1, -1),
    Check("Gerudo Desert South Chest Behind Wooden Gates", -1, -1, -1, -1),
    Check("Gerudo Desert West Canyon Chest", -1, -1, -1, -1),
    Check("Gift From Ralis", -1, -1, -1, -1),
    Check(
        "Goron Mines After Crystal Switch Room Magnet Wall Chest",
        0x804065D0,
        0x2,
        True,
        0x2,
    ),
    Check("Goron Mines Beamos Room Chest", 0x804065D0, 0x10, True, 0x2),
    Check("Goron Mines Chest Before Dangoro", 0x804065D0, 0x20, True, 0x2),
    Check("Goron Mines Crystal Switch Room Small Chest", 0x804065D0, 0x10, True, 0x0),
    Check(
        "Goron Mines Crystal Switch Room Underwater Chest", 0x804065D0, 0x1, True, 0x1
    ),
    Check("Goron Mines Dangoro Chest", 0x804065D0, 0x40, True, 0x3),
    Check("Goron Mines Dungeon Reward", 0x804065D0, 0x8, True, 0x1D),
    Check("Goron Mines Entrance Chest", 0x804065D0, 0x8, True, 0x0),
    Check("Goron Mines Fyrus Heart Container", 0x804065D0, 0x10, True, 0x1D),
    Check("Goron Mines Gor Amato Chest", 0x804065D0, 0x2, True, 0x1),
    Check("Goron Mines Gor Amato Key Shard", 0x804069E0, 0x8, False, -1),
    Check("Goron Mines Gor Amato Small Chest", 0x804065D0, 0x1, True, 0x0),
    Check("Goron Mines Gor Ebizo Chest", 0x804065D0, 0x2, True, 0x0),
    Check("Goron Mines Gor Ezibo Key Shard", 0x804069E7, 0x2, False, -1),
    Check("Goron Mines Gor Liggs Chest", 0x804065D0, 0x4, True, 0x0),
    Check("Goron Mines Gor Liggs Key Shard", 0x804069E7, 0x1, False, -1),
    Check("Goron Mines Magnet Maze Chest", 0x804065D0, 0x10, True, 0x1),
    Check("Goron Mines Main Magnet Room Bottom Chest", 0x804065D0, 0x8, True, 0x2),
    Check("Goron Mines Main Magnet Room Top Chest", 0x804065D0, 0x40, True, 0x0),
    Check("Goron Mines Outside Beamos Chest", 0x804065D0, 0x80, True, 0x2),
    Check("Goron Mines Outside Clawshot Chest", 0x804065D0, 0x40, True, 0x2),
    Check("Goron Mines Outside Underwater Chest", 0x804065D0, 0x20, True, 0x1),
    Check("Goron Springwater Rush", -1, -1, -1, -1),
    Check("Herding Goats Reward", -1, -1, -1, -1),
    Check("Hidden Village Poe", -1, -1, -1, -1),
    Check("Hyrule Castle Big Key Chest", 0x804066B0, 0x1, True, 0x3),
    Check("Hyrule Castle East Wing Balcony Chest", 0x804066B0, 0x8, True, 0x2),
    Check(
        "Hyrule Castle East Wing Boomerang Puzzle Chest", 0x804066B0, 0x10, True, 0x3
    ),
    Check(
        "Hyrule Castle Graveyard Grave Switch Room Back Left Chest",
        0x804066B0,
        0x4,
        True,
        0x7,
    ),
    Check(
        "Hyrule Castle Graveyard Switch Room Front Left Chest",
        0x804066B0,
        0x2,
        True,
        0x7,
    ),
    Check("Hyrule Castle Grave Switch Room Right Chest", 0x804066B0, 0x40, True, 0x0),
    Check("Hyrule Castle King Bulblin Key", 0x804066B0, 0x8, True, 0x3),
    Check("Hyrule Castle Lantern Staircase Chest", 0x804066B0, 0x2, True, 0x0),
    Check("Hyrule Castle Main Hall Northeast Chest", 0x804066B0, 0x1, True, 0x2),
    Check("Hyrule Castle Main Hall Northwest Chest", 0x804066B0, 0x20, True, 0x2),
    Check("Hyrule Castle Southeast Balcony Tower Chest", 0x804066B0, 0x2, True, 0x3),
    Check(
        "Hyrule Castle Treasure Room Eighth Small Chest", 0x804066B0, 0x10, True, 0x0
    ),
    Check("Hyrule Castle Treasure Room Fifth Chest", 0x804066B0, 0x8, True, 0x1),
    Check("Hyrule Castle Treasure Room Fifth Small Chest", 0x804066B0, 0x40, True, 0x1),
    Check("Hyrule Castle Treasure Room First Chest", 0x804066B0, 0x80, True, 0x2),
    Check("Hyrule Castle Treasure Room First Small Chest", 0x804066B0, 0x8, True, 0x7),
    Check("Hyrule Castle Treasure Room Fourth Chest", 0x804066B0, 0x4, True, 0x1),
    Check(
        "Hyrule Castle Treasure Room Fourth Small Chest", 0x804066B0, 0x80, True, 0x1
    ),
    Check("Hyrule Castle Treasure Room Second Chest", 0x804066B0, 0x1, True, 0x1),
    Check(
        "Hyrule Castle Treasure Room Second Small Chest", 0x804066B0, 0x20, True, 0x0
    ),
    Check(
        "Hyrule Castle Treasure Room Seventh Small Chest", 0x804066B0, 0x8, True, 0x0
    ),
    Check("Hyrule Castle Treasure Room Sixth Small Chest", 0x804066B0, 0x4, True, 0x0),
    Check("Hyrule Castle Treasure Room Third Chest", 0x804066B0, 0x2, True, 0x1),
    Check("Hyrule Castle Treasure Room Third Small Chest", 0x804066B0, 0x20, True, 0x1),
    Check(
        "Hyrule Castle West Courtyard Central Small Chest", 0x804066B0, 0x20, True, 0x3
    ),
    Check("Hyrule Castle West Courtyard North Small Chest", 0x804066B0, 0x2, True, 0x2),
    Check("Hyrule Field Amphitheater Owl Statue Chest", -1, -1, -1, -1),
    Check("Hyrule Field Amphitheater Owl Stature Sky Character", -1, -1, -1, -1),
    Check("Hyrule Field Amphitheater Poe", -1, -1, -1, -1),
    Check("Ilia Charm", -1, -1, -1, -1),
    Check("Ilia Memory Reward", -1, -1, -1, -1),
    Check("Isle of Riches Poe", -1, -1, -1, -1),
    Check("Iza Helping Hand", -1, -1, -1, -1),
    Check("Iza Raging Rapids Minigame", -1, -1, -1, -1),
    Check("Jovani 20 Poe Soul Reward", -1, -1, -1, -1),
    Check("Jovani 60 Poe Soul Reward", -1, -1, -1, -1),
    Check("Jovani House Poe", -1, -1, -1, -1),
    Check("Kakariko Gorge Double Clawshot Chest", -1, -1, -1, -1),
    Check("Kakariko Gorge Female Pill Bug", -1, -1, -1, -1),
    Check("Kakariko Gorge Male Pill Bug", -1, -1, -1, -1),
    Check("Kakariko Gorge Owl Statue Chest", -1, -1, -1, -1),
    Check("Kakariko Gorge Owl Statue Sky Character", -1, -1, -1, -1),
    Check("Kakariko Gorge Poe", -1, -1, -1, -1),
    Check("Kakariko Gorge Spire Heart Piece", -1, -1, -1, -1),
    Check("Kakariko Graveyard Golden Wolf", -1, -1, -1, -1),
    Check("Kakariko Graveyard Grave Poe", -1, -1, -1, -1),
    Check("Kakariko Graveyard Lantern Chest", -1, -1, -1, -1),
    Check("Kakariko Graveyard Male Ant", -1, -1, -1, -1),
    Check("Kakariko Graveyard Open Poe", -1, -1, -1, -1),
    Check("Kakariko Inn Chest", -1, -1, -1, -1),
    Check("Kakariko Village Bomb Rock Spire Heart Piece", -1, -1, -1, -1),
    Check("Kakariko Village Bomb Shop Poe", -1, -1, -1, -1),
    Check("Kakariko Village Female Ant", -1, -1, -1, -1),
    Check("Kakariko Village Malo Mart Hawkeye", -1, -1, -1, -1),
    Check("Kakariko Village Malo Mart Hylian Shield", -1, -1, -1, -1),
    Check("Kakariko Village Malo Mart Red Potion", -1, -1, -1, -1),
    Check("Kakariko Village Malo Mart Wooden Shield", -1, -1, -1, -1),
    Check("Kakariko Village Watchtower Poe", -1, -1, -1, -1),
    Check("Lake Hylia Alcove Poe", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Bubble Grotto Chest", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Cliff Chest", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Cliff Poe", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Female Mantis", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Male Mantis", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Owl Statue Chest", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Owl Statue Sky Character", -1, -1, -1, -1),
    Check("Lake Hylia Bridge Vines Chest", -1, -1, -1, -1),
    Check("Lake Hylia Dock Poe", -1, -1, -1, -1),
    Check("Lake Hylia Shell Blade Grotto Chest", -1, -1, -1, -1),
    Check("Lake Hylia Tower Poe", -1, -1, -1, -1),
    Check("Lake Hylia Underwater Chest", -1, -1, -1, -1),
    Check("Lake Hylia Water Toadpoli Grotto Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Eighth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Eleventh Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave End Lantern Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Fifth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Final Poe", -1, -1, -1, -1),
    Check("Lake Lantern Cave First Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Fourteenth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Fourth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Ninth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Second Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Second Poe", -1, -1, -1, -1),
    Check("Lake Lantern Cave Seventh Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Sixth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Tenth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Third Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Thirteenth Chest", -1, -1, -1, -1),
    Check("Lake Lantern Cave Twelfth Chest", -1, -1, -1, -1),
    Check("Lakebed Temple Before Deku Toad Alcove Chest", 0x804065F0, 0x4, True, 0x3),
    Check(
        "Lakebed Temple Before Deku Toad Underwater Left Chest",
        0x804065F0,
        0x80,
        True,
        0x2,
    ),
    Check(
        "Lakebed Temple Before Deku Toad Underwater Right Chest",
        0x804065F0,
        0x40,
        True,
        0x2,
    ),
    Check("Lakebed Temple Big Key Chest", 0x804065F0, 0x10, True, 0x2),
    Check("Lakebed temple Central Room Chest", 0x804065F0, 0x2, True, 0x1),
    Check("Lakebed Temple Central Room Small Chest", 0x804065F0, 0x2, True, 0x3),
    Check("Lakebed Temple Central Room Spire Chest", 0x804065F0, 0x1, True, 0x1),
    Check("Lakebed Temple Chandelier Chest", 0x804065F0, 0x20, True, 0x3),
    Check("Lakebed Temple Deku Toad Chest", 0x804065F0, 0x1, True, 0x3),
    Check("Lakebed Temple Dungeon Reward", 0x804065F0, 0x8, True, 0x1D),
    Check(
        "Lakebed Temple East Lower Waterwheel Bridge Chest", 0x804065F0, 0x1, True, 0x2
    ),
    Check(
        "Lakebed Temple East Lower Waterwheel Stalactite Chest",
        0x804065F0,
        0x40,
        True,
        0x3,
    ),
    Check(
        "Lakebed Temple East Second Floor Southeast Chest", 0x804065F0, 0x4, True, 0x2
    ),
    Check(
        "Lakebed Temple East Second Floor Southwest Chest", 0x804065F0, 0x1, True, 0x0
    ),
    Check(
        "Lakebed Temple East Water Supply Clawshot Chest", 0x804065F0, 0x8, True, 0x2
    ),
    Check("Lakebed Temple East Water Supply Small Chest", 0x804065F0, 0x8, True, 0x0),
    Check("Lakebed Temple Lobby Left Chest", 0x804065F0, 0x10, True, 0x0),
    Check("Lakebed Temple Lobby Rear Chest", 0x804065F0, 0x20, True, 0x0),
    Check("Lakebed Temple Morpheel Heart Container", 0x804065F0, 0x10, True, 0x1D),
    Check("Lakebed Temple Stalactite Room Chest", 0x804065F0, 0x8, True, 0x3),
    Check("Lakebed Temple Underwater Maze Small Chest", 0x804065F0, 0x4, True, 0x1),
    Check("Lakebed Temple West Lower Small Chest", 0x804065F0, 0x40, True, 0x0),
    Check(
        "Lakebed Temple West Second Floor Central Small Chest",
        0x804065F0,
        0x8,
        True,
        0x1,
    ),
    Check(
        "Lakebed Temple West Second Floor Northeast Chest", 0x804065F0, 0x20, True, 0x2
    ),
    Check(
        "Lakebed Temple West Second Floor Southeast Chest", 0x804065F0, 0x8, True, 0x3
    ),
    Check(
        "Lakebed Temple West Second Floor Southwest Underwater Chest",
        0x804065F0,
        0x2,
        True,
        0x0,
    ),
    Check("Lakebed Temple West Water Supply Chest", 0x804065F0, 0x10, True, 0x1),
    Check("Lakebed Temple West Water Supply Small Chest", 0x804065F0, 0x20, True, 0x1),
    Check("Lanayru Field Behind Gate Underwater Chest", -1, -1, -1, -1),
    Check("Lanayru Field Bridge Poe", -1, -1, -1, -1),
    Check("Lanayru Field Female Stag Beetle", -1, -1, -1, -1),
    Check("Lanayru Field Male Stag Beetle", -1, -1, -1, -1),
    Check("Lanayru Field Poe Grotto Left Poe", -1, -1, -1, -1),
    Check("Lanayru Field Poe Grotto Right Poe", -1, -1, -1, -1),
    Check("Lanayru Field Skulltula Grotto Chest", -1, -1, -1, -1),
    Check("Lanayru Field Spinner Track Chest", -1, -1, -1, -1),
    Check("Lanayru Ice Block Puzzle Cave Chest", -1, -1, -1, -1),
    Check("Lanayru Spring Back Room Lantern Chest", -1, -1, -1, -1),
    Check("Lanayru Spring Back Room Left Chest", -1, -1, -1, -1),
    Check("Lanayru Spring Back Room Right Chest", -1, -1, -1, -1),
    Check("Lanayru Spring East Double Clawshot Chest", -1, -1, -1, -1),
    Check("Lanayru Spring Underwater Left Chest", -1, -1, -1, -1),
    Check("Lanayru Spring Underwater Right Chest", -1, -1, -1, -1),
    Check("Lanayru Spring West Double Clawshot Chest", -1, -1, -1, -1),
    Check("Links Basement Chest", -1, -1, -1, -1),
    Check("Lost Woods Boulder Poe", -1, -1, -1, -1),
    Check("Lost Woods Lantern Chest", -1, -1, -1, -1),
    Check("Lost Woods Waterfall Poe", -1, -1, -1, -1),
    Check("Mirror Chamber Mirror Shard", -1, -1, -1, -1),
    Check("North Castle Town Golden Wolf", -1, -1, -1, -1),
    Check("North Faron Woods Deku Baba Chest", -1, -1, -1, -1),
    Check("Ordon Cat Rescue", -1, -1, -1, -1),
    Check("Ordon Ranch Grotto Lantern Chest", -1, -1, -1, -1),
    Check("Ordon Shield", -1, -1, -1, -1),
    Check("Ordon Spring Golden Wolf", -1, -1, -1, -1),
    Check("Ordon Sword", -1, -1, -1, -1),
    Check("Outside Arbiters Grounds Lantern Chest", -1, -1, -1, -1),
    Check("Outside Arbiters Grounds Poe", -1, -1, -1, -1),
    Check("Outside Bulblin Camp Poe", -1, -1, -1, -1),
    Check("Outside Lanayru Spring Left Statue Chest", -1, -1, -1, -1),
    Check("Outside Lanayru Spring Right Statue Chest", -1, -1, -1, -1),
    Check("Outside South Castle Town Double Clawshot Chasm Chest", -1, -1, -1, -1),
    Check("Outside South Castle Town Female Ladybug", -1, -1, -1, -1),
    Check("Outside South Castle Town Fountain Chest", -1, -1, -1, -1),
    Check("Outside South Castle Town Golden Wolf", -1, -1, -1, -1),
    Check("Outside South Castle Town Male Ladybug", -1, -1, -1, -1),
    Check("Outside South Castle Town Poe", -1, -1, -1, -1),
    Check("Outside South Castle Town Tektite Grotto Chest", -1, -1, -1, -1),
    Check("Outside South Castle Town Tightrope Chest", -1, -1, -1, -1),
    Check("Palace of Twilight Big Key Chest", 0x80406690, -1, True, -1),
    Check("Palace of Twilight Central First Room Chest", 0x80406690, -1, True, -1),
    Check("Palace of Twilight Central Outdoor Chest", 0x80406690, -1, True, -1),
    Check("Palace of Twilight Central Tower Chest", 0x80406690, -1, True, -1),
    Check("Palace of Twilight Collect Both Sols", 0x80406690, -1, True, -1),
    Check(
        "Palace of Twilight East Wing First Room East Alcove", 0x80406690, -1, True, -1
    ),
    Check(
        "Palace of Twilight East Wing First Room North Small Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight East Wing First Room West Alcove", 0x80406690, -1, True, -1
    ),
    Check(
        "Palace of Twilight East Wing First Room Zant Head Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight East Wing Second Room Northeast Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight East Wing Second Room Northwest Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight East Wing Second Room Southeast Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight East Wing Second Room Southwest Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight West Wing Chest Behind Wall of Darkness",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight West Wing First Room Central Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight West Wing Second Room Central Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight West Wing Second Room Lower South Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check(
        "Palace of Twilight West Wing Second Room Southeast Chest",
        0x80406690,
        -1,
        True,
        -1,
    ),
    Check("Palace of Twilight Zant Heart Container", 0x80406690, -1, True, -1),
    Check("Plumm Fruit Balloon Minigame", -1, -1, -1, -1),
    Check("Renados Letter", -1, -1, -1, -1),
    Check("Rutelas Blessing", -1, -1, -1, -1),
    Check("Sacred Grove Baba Serpent Grotto Chest", -1, -1, -1, -1),
    Check("Sacred Grove Female Snail", -1, -1, -1, -1),
    Check("Sacred Grove Male Snail", -1, -1, -1, -1),
    Check("Sacred Grove Master Sword Poe", -1, -1, -1, -1),
    Check("Sacred Grove Past Owl Statue Chest", -1, -1, -1, -1),
    Check("Sacred Grove Spinner Chest", -1, -1, -1, -1),
    Check("Sacred Grove Temple of Time Owl Statue Poe", -1, -1, -1, -1),
    Check("Sera Shop Slingshot", -1, -1, -1, -1),
    Check("Skybook From Impaz", -1, -1, -1, -1),
    Check("Snowboard Racing Prize", -1, -1, -1, -1),
    Check("Snowpeak Above Freezard Grotto Poe", -1, -1, -1, -1),
    Check("Snowpeak Blizzard Poe", -1, -1, -1, -1),
    Check("Snowpeak Cave Ice Lantern Chest", -1, -1, -1, -1),
    Check("Snowpeak Cave Ice Poe", -1, -1, -1, -1),
    Check("Snowpeak Freezard Grotto Chest", -1, -1, -1, -1),
    Check("Snowpeak Icy Summit Poe", -1, -1, -1, -1),
    Check("Snowpeak Poe Among Trees", -1, -1, -1, -1),
    Check("Snowpeak Ruins Ball and Chain", -1, -1, True, -1),
    Check("Snowpeak Ruins Blizzeta Heart Container", -1, -1, True, -1),
    Check("Snowpeak Ruins Broken Floor Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Chapel Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Chest After Darkhammer", -1, -1, True, -1),
    Check("Snowpeak Ruins Courtyard Central Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Dungeon Reward", -1, -1, True, -1),
    Check("Snowpeak Ruins East Courtyard Buried Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins East Courtyard Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Ice Room Poe", -1, -1, True, -1),
    Check("Snowpeak Ruins Lobby Armor Poe", -1, -1, True, -1),
    Check("Snowpeak Ruins Lobby Chandelier Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Lobby East Armor Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Lobby Poe", -1, -1, True, -1),
    Check("Snowpeak Ruins Lobby West Armor Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Mansion Map", -1, -1, True, -1),
    Check("Snowpeak Ruins Northeast Chandelier Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Ordon Pumpkin Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins West Cannon Room Central Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins West Cannon Room Corner Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins West Courtyard Buried Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Wooden Beam Central Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Wooden Beam Chandelier Chest", -1, -1, True, -1),
    Check("Snowpeak Ruins Wooden Beam Northwest Chest", -1, -1, True, -1),
    Check("South Faron Cave Chest", -1, -1, -1, -1),
    Check("STAR Prize 1", -1, -1, -1, -1),
    Check("STAR Prize 2", -1, -1, -1, -1),
    Check("Talo Sharpshooting", -1, -1, -1, -1),
    Check("Telma Invoice", -1, -1, -1, -1),
    Check("Temple of Time Armogohma Heart Container", -1, -1, True, -1),
    Check("Temple of Time Armos Antechamber East Chest", -1, -1, True, -1),
    Check("Temple of Time Armos Antechamber North Chest", -1, -1, True, -1),
    Check("Temple of Time Armos Antechamber Statue Chest", -1, -1, True, -1),
    Check("Temple of Time Big Key Chest", -1, -1, True, -1),
    Check("Temple of Time Chest Before Darknut", -1, -1, True, -1),
    Check("Temple of Time Darknut Chest", -1, -1, True, -1),
    Check("Temple of Time Dungeon Reward", -1, -1, True, -1),
    Check("Temple of Time First Staircase Armos Chest", -1, -1, True, -1),
    Check("Temple of Time First Staircase Gohma Gate Chest", -1, -1, True, -1),
    Check("Temple of Time First Staircase Window Chest", -1, -1, True, -1),
    Check("Temple of Time Floor Switch Puzzle Room Upper Chest", -1, -1, True, -1),
    Check("Temple of Time Gilloutine Chest", -1, -1, True, -1),
    Check("Temple of Time Lobby Lantern Chest", -1, -1, True, -1),
    Check("Temple of Time Moving Wall Beamos Room Chest", -1, -1, True, -1),
    Check("Temple of Time Moving Wall Dinalfos Room Chest", -1, -1, True, -1),
    Check("Temple of Time Poe Above Scales", -1, -1, True, -1),
    Check("Temple of Time Poe Behind Gate", -1, -1, True, -1),
    Check("Temple of Time Scales Gohma Chest", -1, -1, True, -1),
    Check("Temple of Time Scales Upper Chest", -1, -1, True, -1),
    Check("Uli Cradle Delivery", -1, -1, -1, -1),
    Check("Upper Zoras River Female Dragonfly", -1, -1, -1, -1),
    Check("Upper Zoras River Poe", -1, -1, -1, -1),
    Check("West Hyrule Field Female Butterfly", -1, -1, -1, -1),
    Check("West Hyrule Field Golden Wolf", -1, -1, -1, -1),
    Check("West Hyrule Field Helmasaur Grotto Chest", -1, -1, -1, -1),
    Check("West Hyrule Field Male Butterfly", -1, -1, -1, -1),
    Check("Wooden Statue", -1, -1, -1, -1),
    Check("Wooden Sword Chest", -1, -1, -1, -1),
    Check("Wrestling With Bo", -1, -1, -1, -1),
    Check("Zoras Domain Chest Behind Waterfall", -1, -1, -1, -1),
    Check("Zoras Domain Chest By Mother and Child Isles", -1, -1, -1, -1),
    Check("Zoras Domain Extinguish All Torches Chest", -1, -1, -1, -1),
    Check("Zoras Domain Light All Torches Chest", -1, -1, -1, -1),
    Check("Zoras Domain Male Dragonfly", -1, -1, -1, -1),
    Check("Zoras Domain Mother and Child Isle Poe", -1, -1, -1, -1),
    Check("Zoras Domain Underwater Goron", -1, -1, -1, -1),
    Check("Zoras Domain Waterfall Poe", -1, -1, -1, -1),
]
